---
format_version: '11'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: ios

pipelines:
  test_pipeline:
    stages:
    - stage_1: {}
    - stage_2: {}

stages:
  stage_1:
    workflows:
    - DecisionMaking: {}
  stage_2:
    workflows:
    - testVble: {}

workflows:
  DecisionMaking:
    description: |
      Wworkflow to test using env vbles across stages
    steps:
    #- activate-ssh-key@4: {}
    - git-clone@7: {}
    - cache-pull@2: {}
    - swiftlint-extended@1:
        inputs:
        - linting_path: $BITRISE_SOURCE_DIR
    #- script@1.1:
    #    title: add variable
    #    inputs:
    #    - content: |
    #        #!/bin/bash -e
    #        set -e
    #        Should_Run=true
    #        envman add --key DEC_MAK --value "$Should_Run"
    - script@1.1:
        title: print variables
        inputs:
        - content: |
            #!/bin/bash -e
            Should_Run=true

            latest_commit_PR=$GIT_CLONE_COMMIT_HASH
            echo "PR commit"
            echo "$latest_commint_PR"

            echo "main commit"
            latest_commint_main=`git log -n 1 main --pretty=format:"%H"`
            echo "$latest_commint_main"
            echo "origin/main commit"
            latest_commint_main_2=`git log -n 1 origin/main --pretty=format:"%H"`
            echo "$latest_commint_main_2"
            

            echo `git diff --name-only $latest_commit_PR $latest_commint_main`

            Should_Run=no

            envman add --key DEC_MAK --value "$Should_Run"
            echo "custom"
            echo "$DEC_MAK"
            echo "$Should_Run"
    - share-pipeline-variable@1:
        inputs:
        - variables: DEC_MAK
  testVble:
    description: |
      workflow to test
    steps:
    #- git-clone@7: {}
    - cache-pull@2: {}
    - script@1.1:
        title: check it warnings
        inputs:
        - content: |
            #!/bin/bash -e
            set -e
            echo "Variable"
            echo $RUN_UI_TESTS
            echo "custom"
            echo "$DEC_MAK"
    - script@1.1:
        title: run conditionally
        run_if: '{{getenv "DEC_MAK" | eq "yes"}}'
        inputs:
        -conten: |
            echo "Hello"
trigger_map:
- push_branch: main
  pipeline: test_pipeline
- pull_request_source_branch: main
  pipeline: test_pipeline
meta:
  bitrise.io:
    stack: osx-xcode-14.1.x-ventura
