---
format_version: '11'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: ios

pipelines:
  test_pipeline:
    stages:
    - stage_1: {}
    - stage_2: {}

stages:
  stage_1:
    workflows:
    - DecisionMaking: {}
  stage_2:
    workflows:
    - testVble: {}

workflows:
  DecisionMaking:
    description: |
      Wworkflow to test using env vbles across stages
    steps:
    #- activate-ssh-key@4: {}
    - git-clone@7: {}
    - cache-pull@2: {}
    #- swiftlint-extended@1:
    #    inputs:
    #    - linting_path: $BITRISE_SOURCE_DIR
    #- script@1.1:
    #    title: add variable
    #    inputs:
    #    - content: |
    #        #!/bin/bash -e
    #        set -e
    #        Should_Run=true
    #        envman add --key DEC_MAK --value "$Should_Run"
    - script@1.1:
        title: DecisionMaking
        inputs:
        - content: |
            #!/usr/bin/env bash
            set -ex
            # Manual triggers leave empty commits. 
            # Check for empty commit/PR and exit blacklist check if found to avoid erroring out.
            echo "files changed"
            echo "$BITRISEIO_GIT_BRANCH_DEST"
            value="hello"

            Run_UI_Tests=$value

            envman add --key RUN_UI_TESTS --value Run_UI_Tests

            FILES_CHANGED_2=$(git diff --name-only origin/release/v111..."$BITRISE_GIT_COMMIT")
            echo "$FILES_CHANGED_2"
            FILES_CHANGED=$(git diff --name-only origin/main..."$BITRISE_GIT_COMMIT")
            echo "Files changed in commit/PR: $FILES_CHANGED"
            if [[ -z "$FILES_CHANGED" ]]; then
                echo "No files changed in commit/PR. Skipping Blacklist check..."
                envman add --key RUN_UI_TESTS --value Run_UI_Tests
                exit 0
            fi
    - script@1.1:
        title: print variables
        is_always_run: true
        run_if: '{{getenv "Run_UI_Tests" | eq "hello" | and .IsBuildFailed}}'
        inputs:
        - content: |
            #!/bin/bash -e
            Should_Run=true

            latest_commit_PR=$GIT_CLONE_COMMIT_HASH
            echo "$latest_commint_PR"

            latest_commint_main=`git log -n 1 origin/main --pretty=format:"%H"`
            echo "$latest_commint_main"
            latest_commint_main-2=`git log -n 1 origin/main --pretty=format:"%H"`
            echo "$latest_commint_main_2"
            

            echo `git diff --name-only $latest_commit_PR $latest_commint_main`

            Should_Run=no

            envman add --key DEC_MAK --value "$Should_Run"
            echo "custom"
            echo "$DEC_MAK"
            echo "$Should_Run"
    - share-pipeline-variable@1:
        inputs:
        - variables: DEC_MAK
  testVble:
    description: |
      workflow to test
    steps:
    #- git-clone@7: {}
    - cache-pull@2: {}
    - script@1.1:
        title: check it warnings
        inputs:
        - content: |
            #!/bin/bash -e
            set -e
            echo "Variable"
            echo $RUN_UI_TESTS
            echo "custom"
            echo "$DEC_MAK"
    - script@1.1:
        title: run conditionally
        run_if: '{{getenv "DEC_MAK" | eq "yes"}}'
        inputs:
        -conten: |
            echo "Hello"
trigger_map:
- push_branch: release/v111
  workflow: DecisionMaking
- push_branch: main
  workflow: DecisionMaking
- pull_request_target_branch: release/v111
  workflow: DecisionMaking
meta:
  bitrise.io:
    stack: osx-xcode-14.1.x-ventura
